package com.karmika.hrms.controller;

import com.karmika.hrms.dto.ApiResponse;
import com.karmika.hrms.entity.Employee;
import com.karmika.hrms.repository.EmployeeRepository;
import com.karmika.hrms.repository.DepartmentRepository;
import com.karmika.hrms.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Map;

@RestController
@RequestMapping("/api/employees")
@RequiredArgsConstructor
public class EmployeeController {

    private final EmployeeRepository employeeRepository;
    private final DepartmentRepository departmentRepository;
    private final UserRepository userRepository;
    private final com.karmika.hrms.service.AuthService authService;

    /**
     * Create new employee (ADMIN & HR only)
     * POST /api/employees/create
     */
    @PostMapping("/create")
    @PreAuthorize("hasAnyRole('ADMIN', 'HR')")
    public ResponseEntity<?> createEmployee(@RequestBody Map<String, Object> employeeData) {
        try {
            Employee employee = new Employee();
            employee.setEmployeeId((String) employeeData.get("employeeId"));
            employee.setFirstName((String) employeeData.get("firstName"));
            employee.setLastName((String) employeeData.get("lastName"));
            employee.setEmail((String) employeeData.get("email"));
            employee.setPhone((String) employeeData.get("phone"));
            employee.setDesignation((String) employeeData.get("designation"));

            // Set department if provided
            if (employeeData.containsKey("departmentId")) {
                Long deptId = Long.valueOf(employeeData.get("departmentId").toString());
                departmentRepository.findById(deptId).ifPresent(employee::setDepartment);
            }

            String autoGeneratedPassword = null;
            // Set user if provided
            if (employeeData.containsKey("userId")) {
                Long userId = Long.valueOf(employeeData.get("userId").toString());
                userRepository.findById(userId).ifPresent(employee::setUser);
            } else if (employee.getEmail() != null) {
                // Create new user automatically
                String roleName = "EMPLOYEE";
                if (employeeData.containsKey("role")) {
                    roleName = (String) employeeData.get("role");
                }
                Map<String, Object> userResult = authService.createUserForEmployee(
                        employee.getFirstName(),
                        employee.getLastName(),
                        employee.getEmail(),
                        roleName);
                com.karmika.hrms.entity.User user = (com.karmika.hrms.entity.User) userResult.get("user");
                autoGeneratedPassword = (String) userResult.get("rawPassword");
                employee.setUser(user);
            }

            Employee savedEmployee = employeeRepository.save(employee);

            Map<String, Object> response = new java.util.HashMap<>();
            response.put("success", true);
            response.put("message", "Employee created successfully");
            response.put("employee", savedEmployee);

            if (autoGeneratedPassword != null) {
                response.put("autoGeneratedPassword", autoGeneratedPassword);
                response.put("generatedUsername", savedEmployee.getUser().getUsername());
                response.put("message",
                        "Employee created successfully. Auto-generated password: " + autoGeneratedPassword);
            }

            return ResponseEntity.ok(response);
        } catch (Exception e) {
            return ResponseEntity.badRequest().body(Map.of(
                    "success", false,
                    "error", e.getMessage()));
        }
    }

    /**
     * Update employee (ADMIN & HR only)
     * PUT /api/employees/update/{id}
     */
    @PutMapping("/update/{id}")
    @PreAuthorize("hasAnyRole('ADMIN', 'HR')")
    public ResponseEntity<?> updateEmployee(@PathVariable Long id, @RequestBody Map<String, Object> employeeData) {
        return employeeRepository.findById(id)
                .map(employee -> {
                    // Update fields
                    if (employeeData.containsKey("firstName"))
                        employee.setFirstName((String) employeeData.get("firstName"));
                    if (employeeData.containsKey("lastName"))
                        employee.setLastName((String) employeeData.get("lastName"));
                    if (employeeData.containsKey("email"))
                        employee.setEmail((String) employeeData.get("email"));
                    if (employeeData.containsKey("phone"))
                        employee.setPhone((String) employeeData.get("phone"));
                    if (employeeData.containsKey("designation"))
                        employee.setDesignation((String) employeeData.get("designation"));
                    if (employeeData.containsKey("address"))
                        employee.setAddress((String) employeeData.get("address"));

                    // Update department
                    if (employeeData.containsKey("departmentId")) {
                        Long deptId = Long.valueOf(employeeData.get("departmentId").toString());
                        departmentRepository.findById(deptId).ifPresent(employee::setDepartment);
                    }

                    Employee updated = employeeRepository.save(employee);
                    return ResponseEntity.ok(Map.of(
                            "success", true,
                            "message", "Employee updated successfully",
                            "employee", updated));
                })
                .orElse(ResponseEntity.notFound().build());
    }

    /**
     * Get all employees (ADMIN, HR, MANAGER)
     * GET /api/employees/list
     */
    @GetMapping("/list")
    @PreAuthorize("hasAnyRole('ADMIN', 'HR', 'MANAGER')")
    public ResponseEntity<List<Employee>> getAllEmployees() {
        return ResponseEntity.ok(employeeRepository.findAll());
    }

    /**
     * Get employee by ID (ADMIN, HR, MANAGER)
     * GET /api/employees/view/{id}
     */
    @GetMapping("/view/{id}")
    @PreAuthorize("hasAnyRole('ADMIN', 'HR', 'MANAGER')")
    public ResponseEntity<?> getEmployeeById(@PathVariable Long id) {
        return employeeRepository.findById(id)
                .map(employee -> ResponseEntity.ok(Map.of(
                        "success", true,
                        "employee", employee)))
                .orElse(ResponseEntity.notFound().build());
    }

    /**
     * Search employees by name or email
     * GET /api/employees/search?query=john
     */
    @GetMapping("/search")
    @PreAuthorize("hasAnyRole('ADMIN', 'HR', 'MANAGER')")
    public ResponseEntity<List<Employee>> searchEmployees(@RequestParam String query) {
        // Simple search - can be enhanced with repository method
        List<Employee> allEmployees = employeeRepository.findAll();
        List<Employee> results = allEmployees.stream()
                .filter(emp -> emp.getFirstName().toLowerCase().contains(query.toLowerCase()) ||
                        emp.getLastName().toLowerCase().contains(query.toLowerCase()) ||
                        emp.getEmail().toLowerCase().contains(query.toLowerCase()))
                .toList();
        return ResponseEntity.ok(results);
    }

    /**
     * Get employees by department
     * GET /api/employees/department/{departmentId}
     */
    @GetMapping("/department/{departmentId}")
    @PreAuthorize("hasAnyRole('ADMIN', 'HR', 'MANAGER')")
    public ResponseEntity<List<Employee>> getEmployeesByDepartment(@PathVariable Long departmentId) {
        List<Employee> employees = employeeRepository.findAll().stream()
                .filter(emp -> emp.getDepartment() != null && emp.getDepartment().getId().equals(departmentId))
                .toList();
        return ResponseEntity.ok(employees);
    }

    /**
     * Get employee count
     * GET /api/employees/count
     */
    @GetMapping("/count")
    @PreAuthorize("hasAnyRole('ADMIN', 'HR')")
    public ResponseEntity<?> getEmployeeCount() {
        long count = employeeRepository.count();
        long activeCount = employeeRepository.findAll().stream()
                .filter(emp -> emp.getStatus() == Employee.EmployeeStatus.ACTIVE)
                .count();

        return ResponseEntity.ok(Map.of(
                "totalEmployees", count,
                "activeEmployees", activeCount));
    }

    /**
     * Deactivate employee (Soft delete)
     * PUT /api/employees/deactivate/{id}
     */
    @PutMapping("/deactivate/{id}")
    @PreAuthorize("hasAnyRole('ADMIN', 'HR')")
    public ResponseEntity<?> deactivateEmployee(@PathVariable Long id) {
        return employeeRepository.findById(id)
                .map(employee -> {
                    employee.setStatus(Employee.EmployeeStatus.EXITED);
                    employeeRepository.save(employee);
                    return ResponseEntity.ok(new ApiResponse(true, "Employee deactivated successfully"));
                })
                .orElse(ResponseEntity.notFound().build());
    }

    /**
     * Activate employee
     * PUT /api/employees/activate/{id}
     */
    @PutMapping("/activate/{id}")
    @PreAuthorize("hasAnyRole('ADMIN', 'HR')")
    public ResponseEntity<?> activateEmployee(@PathVariable Long id) {
        return employeeRepository.findById(id)
                .map(employee -> {
                    employee.setStatus(Employee.EmployeeStatus.ACTIVE);
                    employeeRepository.save(employee);
                    return ResponseEntity.ok(new ApiResponse(true, "Employee activated successfully"));
                })
                .orElse(ResponseEntity.notFound().build());
    }

    /**
     * Get current logged-in employee profile
     * GET /api/employees/me
     */
    @GetMapping("/me")
    public ResponseEntity<?> getMyProfile(Authentication auth) {
        String username = auth.getName();
        return employeeRepository.findAll().stream()
                .filter(emp -> emp.getUser() != null && emp.getUser().getUsername().equals(username))
                .findFirst()
                .map(employee -> ResponseEntity.ok(Map.of(
                        "success", true,
                        "employee", employee)))
                .orElse(ResponseEntity.notFound().build());
    }

    /**
     * Get my team members (MANAGER only)
     * GET /api/employees/my-team
     */
    @GetMapping("/my-team")
    @PreAuthorize("hasAnyRole('MANAGER', 'ADMIN', 'HR')")
    public ResponseEntity<?> getMyTeam(Authentication auth) {
        try {
            String username = auth.getName();
            Employee manager = employeeRepository.findAll().stream()
                    .filter(emp -> emp.getUser() != null && emp.getUser().getUsername().equals(username))
                    .findFirst()
                    .orElseThrow(() -> new RuntimeException("Manager not found"));

            List<Employee> team = employeeRepository.findAll().stream()
                    .filter(emp -> emp.getReportingManager() != null &&
                            emp.getReportingManager().getId().equals(manager.getId()))
                    .toList();

            return ResponseEntity.ok(team);
        } catch (Exception e) {
            return ResponseEntity.badRequest().body(Map.of("error", e.getMessage()));
        }
    }

    /**
     * Update profile photo
     * PUT /api/employees/profile-photo
     */
    @PutMapping("/profile-photo")
    public ResponseEntity<?> updateProfilePhoto(@RequestBody Map<String, String> data, Authentication auth) {
        try {
            String username = auth.getName();
            String photoUrl = data.get("photoUrl");

            if (photoUrl == null || photoUrl.isEmpty()) {
                return ResponseEntity.badRequest().body(Map.of("success", false, "error", "Photo URL is required"));
            }

            return employeeRepository.findAll().stream()
                    .filter(emp -> emp.getUser() != null && emp.getUser().getUsername().equals(username))
                    .findFirst()
                    .map(employee -> {
                        employee.setPhotoUrl(photoUrl);
                        employeeRepository.save(employee);
                        return ResponseEntity.ok(Map.of(
                                "success", true,
                                "message", "Profile photo updated successfully",
                                "photoUrl", photoUrl));
                    })
                    .orElse(ResponseEntity.notFound().build());
        } catch (Exception e) {
            return ResponseEntity.badRequest().body(Map.of("success", false, "error", e.getMessage()));
        }
    }

    /**
     * Assign employee to manager (HR & ADMIN only)
     * PUT /api/employees/assign-manager/{employeeId}
     */
    @PutMapping("/assign-manager/{employeeId}")
    @PreAuthorize("hasAnyRole('ADMIN', 'HR')")
    public ResponseEntity<?> assignEmployeeToManager(
            @PathVariable Long employeeId,
            @RequestBody Map<String, Object> data) {
        try {
            Long managerId = data.containsKey("managerId") && data.get("managerId") != null
                    ? Long.valueOf(data.get("managerId").toString())
                    : null;

            return employeeRepository.findById(employeeId)
                    .map(employee -> {
                        if (managerId == null) {
                            // Remove manager assignment
                            employee.setReportingManager(null);
                        } else {
                            // Assign to manager
                            Employee manager = employeeRepository.findById(managerId)
                                    .orElseThrow(() -> new RuntimeException("Manager not found"));

                            // Verify the manager has manager/admin/hr role
                            if (manager.getUser() != null) {
                                String role = manager.getUser().getRole().name();
                                if (!role.equals("MANAGER") && !role.equals("ADMIN") && !role.equals("HR")) {
                                    return ResponseEntity.badRequest().body(Map.of(
                                            "success", false,
                                            "error", "Selected employee must have MANAGER, ADMIN, or HR role"));
                                }
                            }

                            employee.setReportingManager(manager);
                        }

                        employeeRepository.save(employee);

                        return ResponseEntity.ok(Map.of(
                                "success", true,
                                "message",
                                managerId == null ? "Manager assignment removed successfully"
                                        : "Employee assigned to manager successfully",
                                "employee", employee));
                    })
                    .orElse(ResponseEntity.notFound().build());
        } catch (Exception e) {
            return ResponseEntity.badRequest().body(Map.of(
                    "success", false,
                    "error", e.getMessage()));
        }
    }
}
